name: Download artifacts 
on:
  workflow_dispatch:   
  push:              

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload artifact
        run: pwd
          
             
             
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: zip project.zip         
          path: artifact-download/ 

    
      - name: Show downloaded files
        run: ls artifact-download/
