name: Download artifacts 
on:
 workflow_dispatch:
    inputs:
      source_run_id:
        description: "Workflow run ID to pull artifacts from"
        required: true
        type: string    # run IDs are numeric, but dispatch inputs are strings 

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload artifact
        run: pwd
          
             
             
      - name: Download artifact from another run
        uses: actions/download-artifact@v4
        with:
          name: project-zip                  # the artifact name in that run
          run-id: ${{ inputs.source_run_id }} # e.g., supplied via workflow_dispatch input
          path: artifact-download/
          github-token: ${{ secrets.PAT }}    # fine-grained PAT with Actions:read (or repo scope for classic) 

    
      - name: Show downloaded files
        run: ls artifact-download/
